### ISSUE TITLE
Add design

### ISSUE THREAD

**Issue by aahutsal** [gutsal-arsen/raphael-elvanto#10]
Attached. As the menu use `/` and `/search` contexts only as for now.
[themeforest-8437259-angulr-bootstrap-admin-web-app-with-angularjs.zip](https://github.com/gutsal-arsen/raphael-elvanto/files/204036/themeforest-8437259-angulr-bootstrap-admin-web-app-with-angularjs.zip)

**Comment by vitalyp** [comment]
It sounds ambiguous. Please give a directly point to necessary updates for / and /search context links.
( update: it seems it relates to sketches listed in  #12 ? )

**Comment by aahutsal** [comment]
Well, I meant that our /search and /index pages will be redone using our design (use Grid or Dynamic T ables for `<table/>` tag, other is clear it seems). So I expect that you redo layout.jade, index.jade and search.jade. Also add the menu at left that points to `/index` and `/search` contexts.
Think you can use this tool http://html2jade.org/ to get HTML converted to jade faster.

**Comment by aahutsal** [comment]
@MaxKomar 
- On `/search` page try to perfrom city search providing `Corona` as city name. I need results to be dsplayed as dynamic grid (check original design, file attached).
- Remove red [2] bubble at top right corner that always appear saying we have 2 messages
- Replace `John.Smith` with `Raphael.Maher`
- Make left side pannel (where we have `Import contacts` and `Search`) hidding when button pressed (check original design).
