### ISSUE TITLE
Optimize code using require('async')

### ISSUE THREAD

**Issue by aahutsal** [gutsal-arsen/raphael-elvanto#17]
There are 2 places in the code that should be reworked using `require('async')`. One place is where we store into Mongo during contact import from Elvanto. Another place is where we store into Google contacts. In each case there should be some constant set, that runs N separate threas using `require('async')`. All threads should share some delay (D), so that for eample for Elvanto -> Mongo import we don't overlap 10 req/sec (we use geoCoder inside, and it's sensitive to 10 req/sec). Same for other case.

**Comment by vitalyp** [comment]
Elvanto_to_Google Optimized https://github.com/gutsal-arsen/raphael-elvanto/commit/0d7030368d46a4815f3262d0a5fa1f3f57e58352

**Comment by aahutsal** [comment]
Rework store to Mongo this way also.

**Comment by vitalyp** [comment]
Elvanto_to_Mongo https://github.com/gutsal-arsen/raphael-elvanto/commit/09a2d83103e026e73408162dcd7a50c104a72340
