### ISSUE TITLE
Start using Maps API key. Add http://www.copticcollection.org:3000/search to your Google Map API allowed hosts

### ISSUE THREAD

**Issue by aahutsal** [gutsal-arsen/raphael-elvanto#6]
Generate Maps API key. Use it.
Add these hosts to your Google Map API allowed hosts

`http://*.copticcollection.org:3000`
`http://*.copticcollection.org`

**Comment by aahutsal** [comment]
I've already hardcoded `?key=XXX` with my own Maps API key. Make ti configurable through `.env`. Use `GOOGLE_SERVER_API_KEY` variable.

**Comment by vitalyp** [comment]
done by https://github.com/gutsal-arsen/raphael-elvanto/commit/2d6eed69622b728486ed8bface8bd25659625196
