### ISSUE TITLE
Elvanto to Google Contacts

### ISSUE THREAD

**Issue by aahutsal** [gutsal-arsen/raphael-elvanto#9]
Modify Elvanto import script in a way that let us store Person as Google Contacts entry. Check Google Contacts API docs: http://bit.ly/1VpXi3Z

You can look for some existing NPM module and use it. You need Google AccessToken for that task. Please, use yours but make it configurable and stored in external file (which is added to .gitignore). If file does not exist or has empty AccessToken application should fail on start with an appropriate message.

**Comment by vitalyp** [comment]
can't find proper NPM module for this task, any suggestions are welcome

**Comment by aahutsal** [comment]
@vitalyp most of the code that creates XML is already in `master` branch. Merge it back to `google_contacts` and find what's the reason our `response.post` does not actually post data to server.

**Comment by vitalyp** [comment]
fixed by this commit https://github.com/gutsal-arsen/raphael-elvanto/commit/e2c5c9a86d87827df54faf4f1a48330b59a514c9
Also, I got <User Rate Limit Exceeded> for my API usage, after 92 contacts were created

**Comment by aahutsal** [comment]
@vitalyp got what?

**Comment by vitalyp** [comment]
Also, I got 'User Rate Limit Exceeded' for my API usage, after 92 contacts were created
